-- RECREATE SETORES TABLE (V2)
-- Drops existing table and recreates with support for:
-- 1. Numeric IDs (BigInt)
-- 2. Duplicate Radio Codes (differentiated by Team/Shift)
-- 3. Numeric Critical Level (1-4)

DROP TABLE IF EXISTS setores CASCADE;

CREATE TABLE setores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_radio TEXT NOT NULL,          -- Ex: "Alfa 01" (Pode repetir)
    nome TEXT,                           -- Ex: "Bloco A - Térreo" (Descritivo)
    campus TEXT,                         -- Ex: "Campus I"
    equipe TEXT,                         -- Ex: "A", "B", "ADM" (Diferenciador 1)
    turno TEXT,                          -- Ex: "DIURNO", "NOTURNO" (Diferenciador 2)
    nivel_critico INTEGER DEFAULT 0,     -- 0=Baixo, 1=Médio, 2=Alto, 3=Crítico (Ajustável)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS (Security)
ALTER TABLE setores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read" ON setores FOR SELECT USING (true);
CREATE POLICY "Authenticated Write" ON setores FOR ALL USING (auth.role() = 'authenticated');

-- Grant permissions
GRANT ALL ON setores TO postgres, anon, authenticated;
GRANT ALL ON SEQUENCE setores_id_seq TO postgres, anon, authenticated;

SELECT 'Tabela SETORES recriada com sucesso!' as result;
